hello:
  text: hello

api:
  baseUrl: http://localhost:8081
  mono:
    mono-just:
      url: /monoJust
    mono-zip:
      url: /monoZip
    flux-just:
      url: /FluxJust
    flux-zip:
      url: /FluxZip
    flux-interval:
      url: /FluxInterval





